# Generated by Django 2.0.3 on 2018-03-19 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoMarketCap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_coin_type', models.CharField(max_length=10)),
                ('to_coin_type', models.CharField(max_length=10)),
                ('current_marketcap', models.CharField(max_length=20)),
                ('previous_marketcap', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoPriceAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_coin_type', models.CharField(max_length=10)),
                ('to_coin_type', models.CharField(max_length=10)),
                ('current_price', models.CharField(max_length=20)),
                ('previous_price', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoVolumePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_coin_type', models.CharField(max_length=10)),
                ('to_coin_type', models.CharField(max_length=10)),
                ('current_volume', models.CharField(max_length=20)),
                ('previous_volume', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='QueryTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dynamic_query', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='querytable',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert.UserTable'),
        ),
    ]
